### ISSUE TITLE
Conflict with PyPI Routes

### ISSUE THREAD

**Issue by jayvdb** [khornberg/octokitpy-routes#61]
Installing into 'routes' directory conflicts with PyPI [Routes](https://pypi.org/project/Routes/) package, at https://github.com/bbangert/routes.

**Comment by khornberg** [comment]
Thanks I'll have to change that

**Comment by khornberg** [comment]
Version 2.0.0 of this package fixes the direct issue.

If you are using [octokit.py](https://github.com/khornberg/octokit.py) that is not updated since the underlying route packages had breaking changes

**Comment by jayvdb** [comment]
Thanks for the quick response.  I'm happy to wait until the next release of octokit.py
